package com.bootcoding.dsa.leetcodel1;

/*
Leetcode Q-3270 WAP to Find the key of the numbers
You are given three positive integers num1, num2, and num3.
The key of num1, num2, and num3 is defined as a four-digit number such that:
Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among
the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).
 */
public class FindKeyOfNumbers {
    public static void main(String[] args) {
        int num1 = 1;
        int num2 = 10;
        int num3 = 1000;
        //Method Calling
        int result = generateKey(num1,num2,num3);
        System.out.println(result);
    }

    //Method Definition
    public static int generateKey(int num1, int num2, int num3) {

        int[] digits1 = getDigits(num1);
        int[] digits2 = getDigits(num2);
        int[] digits3 = getDigits(num3);

        int result = 0;

        for (int i = 0; i < 4; i++) {
            int minDigit = Math.min(digits1[i], Math.min(digits2[i], digits3[i]));
            result = result * 10 + minDigit;
        }

        return result;
    }

    private static int[] getDigits(int num){
        int[] digits = new int[4];

        for(int i = 3; i >= 0 && num > 0; i--){
            digits[i] = num % 10;
            num /= 10;
        }

        return digits;
    }
}
